language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
env:
  - DJANGO="Django>=1.4,<1.5"
  - DJANGO="Django>=1.5,<1.6"
  - DJANGO="Django>=1.6,<1.7"
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO="Django>=1.4,<1.5"
    - python: "3.4"
      env: DJANGO="Django>=1.4,<1.5"
before_install:
  - PWD=`pwd`
  - "echo '## Installing dependencies'"
  - "sudo apt-get update"
  - "sudo apt-get install -y openssl build-essential xorg libssl-dev xfonts-75dpi"
  - "echo '## Downloading wkhtmltopdf'"
  - "wget http://download.gna.org/wkhtmltopdf/0.12/0.12.2.1/wkhtmltox-0.12.2.1_linux-wheezy-amd64.deb"
  - "echo '## Installing wkhtmltox'"
  - "sudo dpkg -i wkhtmltox-0.12.2.1_linux-wheezy-amd64.deb"
  - WHICH_WK=`which wkhtmltopdf`
  - "export WKHTMLTOPDF_CMD=$WHICH_WK"
install:
  - pip install $DJANGO
  - pip install -r test_requirements.txt
  - pip install .
script:
  - make test
notifications:
  email: false
